#---
#- hosts: dbserver
# become: yes
# roles:
#   - role: 'roles/HSC/monitoring'
#     tags:
#       - hold_HSC
#   - role: 'roles/common/webtier'
#   - role: 'roles/common/nginx_hardening'
#     tags:
#       - hold_common
---
- hosts: dbserver
  become: yes
  tasks:
  - name: Install apache packages
    yum:
     name: httpd
     state: present

  - name: Start httpd
    service:
     name: httpd
     state: started

  - name: Open port 80 for http access
    firewalld:
    service: http
     permanent: true
     state: enabled

  - name: Restart firewalld service to load firewall changes
    service:
     name: firewalld
     state: reloaded 
